name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: go mod download

      - name: Test
        run: task test
