name: GoLic
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
jobs:
  GoLic:
    name: GoLic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GoLic
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/Bugs5382/golic/cmd/golic@v0.2.0
          ./bin/golic inject -c "{projects lic string}" -t {template} -d
